### ISSUE TITLE
Crash to desktop when launching DCS World with support for eye tracker enabled

### ISSUE THREAD

**Issue by madamjanus** [mbucchia/OpenXR-Eye-Trackers#1]
Crash to desktop when launching DCS World with support for eye tracker enabled
[OpenXR-Eye-Trackers.log](https://github.com/mbucchia/OpenXR-Eye-Trackers/files/12640859/OpenXR-Eye-Trackers.log)

**Comment by mbucchia** [comment]
I've tested this many times with DCS and Pimax without issue. I suspect it's perhaps due to an incompatibility with something else you have installed. 

For all other OpenXR API layers (eg: Quad-Views-Foveated), can you also attach the logs?

**Comment by madamjanus** [comment]
[OpenXR-Eye-Trackers.log](https://github.com/mbucchia/OpenXR-Eye-Trackers/files/12641533/OpenXR-Eye-Trackers.log)
[Quad-Views-Foveated.log](https://github.com/mbucchia/OpenXR-Eye-Trackers/files/12641534/Quad-Views-Foveated.log)
[XR_APILAYER_MBUCCHIA_toolkit.log](https://github.com/mbucchia/OpenXR-Eye-Trackers/files/12641537/XR_APILAYER_MBUCCHIA_toolkit.log)

**Comment by mbucchia** [comment]
Thanks. I suspect the issue might be with OpenXR Toolkit. Can you try disabling it and see if the crash still occurs? If so, can you make sure to reset all OpenXR Toolkit settings to default (via Safe Mode).

**Comment by mbucchia** [comment]
No reply. Closing.
