### ISSUE TITLE
Eye Tracking Test Tool Works - Doesnt work on Vrchat

### ISSUE THREAD

**Issue by Tyillucio** [mbucchia/OpenXR-Eye-Trackers#3]
I'm using a custom Gary Mod world Avatar with eye tracking and a quest pro option on the avatar. But I can't get any response but closed eye lids or open eyelids.

When I use the troubleshoot program it's working perfectly via virtual desktop. Is there a step I'm missing to utilize the tool?

**Comment by mbucchia** [comment]
1) VRChat isn't OpenXR. So I think this program is completely irrelevant to you.

2) This is an eye tracking, not face tracking program. Eye tracking = the use of eye gaze for the purpose of pointing. You're not going to get eye lid info, this would require face tracking.
